name = "ReusableFunctions"
uuid = "afbf81f7-602f-5a4a-9a77-738a1b1188fe"
version = "1.0.2"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
DataStructures = "0.17, 0.18, 0.19"
FileIO = "1"
JLD2 = "0.2, 0.3, 0.4, 0.5"
Suppressor = "0.2, 0.3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
